spring:
  application:
    name: ParkEasy

  datasource:
    url: jdbc:mysql://localhost:3307/parkeasy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: parkeasy123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update  # SPRING KREIRA TABELE AUTOMATSKI!
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 20
    show-sql: true

  redis:
    host: localhost
    port: 6379
    timeout: 2000ms

server:
  port: 8080

logging:
  level:
    com.parkeasy: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE